import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./_components/Header";
import { StaffProvider } from "./_context/StaffContext";
import { Toaster } from "sonner";
import { UserProvider } from "./_context/UserContext";
import AppointmentsProvider from "./_context/AppointmentContext";
import { ServiceProvider } from "./_context/ServiceContext";
import { Footer } from "./_components/LayoutFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#eaeaea]`}
      >
        <div className="max-w-[768px] m-auto min-h-screen">
          <Toaster />
          <AppointmentsProvider>
            <UserProvider>
              <StaffProvider>
                <ServiceProvider>
                  <Header />
                  {children}
                  <Footer />
                </ServiceProvider>
              </StaffProvider>
            </UserProvider>
          </AppointmentsProvider>
        </div>
      </body>
    </html>
  );
}
